; =====================================================
; ATACANTE — game-atacante
; NodeMCU ESP8266 + Botão PBS-29 + Laser KY-008 + Buzzer
; Ambiente: VS Code + PlatformIO (Windows)
; =====================================================
[env:nodemcuv2]
platform      = espressif8266
board         = nodemcuv2
framework     = arduino

monitor_speed = 9600
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient   @ ^2.8
    bblanchon/ArduinoJson    @ ^6.21.3
